ALTER TABLE Multimedia ADD OriginalDate DATETIME NULL;
ALTER TABLE Multimedia ADD CameraMake VARCHAR(255) NULL;
ALTER TABLE Multimedia ADD CameraModel VARCHAR(255) NULL;
ALTER TABLE Multimedia ADD GPSLatitudeRef VARCHAR(1) NULL;
ALTER TABLE Multimedia ADD GPSLatitude VARCHAR(32) NULL;
ALTER TABLE Multimedia ADD GPSLongitudeRef VARCHAR(1) NULL;
ALTER TABLE Multimedia ADD GPSLongitude VARCHAR(32) NULL;
