CREATE TABLE metrics(
  Id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  capturetime timestamp NOT NULL,
  memoryInit double,
  memoryMax double,
  memoryUsed double,
  memoryCommitted double,
  heapInit double,
  heapMax double,
  heapUsed double,
  heapCommitted double,
  heapUsage double,
  nonHeapUsage double,
  activeRequests integer,
  maxDbConnections integer,
  idleDbConnections integer,
  openDbConnections integer,
  uptime double,
  daemonThreadCount integer,
  threadCount integer,
  totalStartedThreadCount bigint,
  processCpuTime double,
  systemCpuLoad double,
  processCpuLoad double,
  committedVirtualMemorySize bigint,
  openFileDescriptorCount bigint,
  maxFileDescriptorCount bigint,
  systemLoadAverage double,
  peakThreadCount int,
  loadedClassCount int,
  totalLoadedClassCount bigint,
  unloadedClassCount bigint
);

CREATE INDEX capturetime_index ON metrics(capturetime);
